title: "Analyzing Inflation and Economic Trends: A Comparative Data Analysis of U.S. and German CPI, GDP, and Inflation Across Presidential and Chancellor Tenures"
description: Github website
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
